import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { createFixerTestDb } from './fixer-test-db'
import { canonicalJson } from '../src/lib/hermes/requestPayload'

async function main() {
  const db = await createFixerTestDb()
  const user = randomUUID(), other = randomUUID(), estimate = randomUUID(), estimate2 = randomUUID()
  await db.query('insert into users values($1),($2)', [user, other])
  await db.query('insert into estimates(id,lead_id) values($1,$3),($2,$3)', [estimate, estimate2, randomUUID()])
  const scalar = async <T>(sql: string, args: unknown[] = []) => (await db.query<{ value: T }>(sql, args)).rows[0]?.value
  const enqueue = (id: string, eid = estimate, uid = user) => scalar<Record<string, unknown>>(
    "select enqueue_fixer_request($1,$2,$3,'Price framing') as value", [id, uid, eid])
  const claim = () => scalar<{ id: string; lease_token: string }>('select claim_fixer_request() as value')
  const update = (id: string, lease: string, action: string, text: string) => scalar<boolean>(
    'select update_fixer_request($1,$2,$3,$4) as value', [id, lease, action, text])
  const id = randomUUID()
  const queued = await enqueue(id)
  assert.equal(queued.status, 'queued')
  assert.equal(queued.lease_token, undefined, 'Submission must never reveal worker credential')
  assert.equal((await enqueue(id)).id, id, 'Lost submission acknowledgment is idempotent')
  await assert.rejects(enqueue(id, estimate2), /Id already used/)
  await assert.rejects(enqueue(randomUUID(), estimate, other), /fixer_one_active_per_estimate/)
  const second = randomUUID()
  await enqueue(second, estimate2, other)
  const job = await claim()
  assert.equal(job.id, id)
  assert.equal((await claim()).id, second)
  assert.equal(await claim(), null, 'A claimed request is never executed twice')
  assert.equal(await update(id, randomUUID(), 'complete', 'bad'), false, 'Wrong worker cannot finish')
  const payload = [{ description: 'Framing', name_status: 'sourced', uom: 'EA', quantity: 2,
    unit_cost: 30, labor_cost: 10, material_cost: 15, sub_cost: 5, markup_pct: 10, sort_order: 0, source: 'ai_comp' }]
  const stage = (lease = job.lease_token, hash = 'same') => scalar<number>(
    'select stage_fixer_lines($1,$2,$3,$4::jsonb) as value', [id, lease, hash, JSON.stringify(payload)])
  assert.equal(await stage(), 1)
  assert.equal(await stage(), 1, 'Retry returns existing batch')
  const count = (table: string) => scalar<number>(`select count(*)::int as value from ${table}`)
  assert.equal(await count('estimate_lines'), 0, 'Background work never directly writes lines')
  assert.equal(await count('estimate_line_proposals'), 1)
  await assert.rejects(stage(randomUUID(), 'bad'), /lease no longer valid/)
  const proposal = await scalar<string>('select id as value from estimate_line_proposals')
  const approve = () => scalar<Array<Record<string, unknown>>>('select apply_estimate_proposals($1,$2) as value', [[proposal], user])
  const first = await approve()
  const again = await approve()
  assert.equal(first[0].id, again[0].id, 'Repeated approval returns the already-applied line')
  assert.equal(await count('estimate_lines'), 1)
  assert.equal(Number(first[0].labor_cost), 10)
  assert.equal(Number(first[0].material_cost), 15)
  assert.equal(Number(first[0].sub_cost), 5)
  await stage()
  assert.equal(await count('estimate_line_proposals'), 1, 'Applied batch cannot be restaged')
  assert.equal(await update(id, job.lease_token, 'complete', 'Saved answer'), true)
  assert.equal(await update(id, job.lease_token, 'complete', 'Saved answer'), true)
  assert.equal(await update(id, job.lease_token, 'complete', 'Different answer'), false)
  await assert.rejects(stage(job.lease_token, 'late'), /lease no longer valid/)
  const recovered = await db.query('select message,result,status from fixer_requests where user_id=$1 and estimate_id=$2', [user, estimate])
  assert.deepEqual(recovered.rows, [{ message: 'Price framing', result: 'Saved answer', status: 'completed' }], 'A new reader recovers question and answer without a live connection')
  assert.equal((await db.query('select id from fixer_requests where user_id=$1 and estimate_id=$2', [other, estimate])).rows.length, 0)
  await db.query("update fixer_requests set lease_until=now()-interval '1 minute' where id=$1", [second])
  await db.exec('select expire_fixer_requests()')
  assert.equal(await scalar('select status as value from fixer_requests where id=$1', [second]), 'failed')
  const retry = randomUUID()
  await enqueue(retry)
  const retryJob = await claim()
  await db.query('update estimates set is_locked=true where id=$1', [estimate])
  await assert.rejects(scalar('select stage_fixer_lines($1,$2,$3,$4::jsonb) as value', [retry, retryJob.lease_token, 'locked', JSON.stringify(payload)]), /locked/)
  await assert.rejects(enqueue(randomUUID()), /unavailable/)
  await db.query('update estimates set is_locked=false where id=$1', [estimate])
  await update(retry, retryJob.lease_token, 'fail', 'Interrupted')
  const neverStarted = randomUUID()
  await enqueue(neverStarted)
  await db.query("update fixer_requests set created_at=now()-interval '16 minutes' where id=$1", [neverStarted])
  await db.exec('select expire_fixer_requests()')
  assert.equal(await scalar('select status as value from fixer_requests where id=$1', [neverStarted]), 'failed')

  for (const role of ['anon', 'authenticated']) {
    await db.exec(`set role ${role}`)
    await assert.rejects(db.exec('select * from fixer_requests'), /permission denied/)
    await assert.rejects(db.exec('select * from fixer_worker_health'), /permission denied/)
    await assert.rejects(db.exec('select claim_fixer_request()'), /permission denied/)
    await assert.rejects(db.exec('select expire_fixer_requests()'), /permission denied/)
    await db.exec('reset role')
  }
  await db.exec('set role service_role')
  assert.equal(await claim(), null, 'Invoker RPC works with actual worker role')
  await db.exec('reset role')
  assert.equal(canonicalJson([{ b: 2, a: 1 }]), canonicalJson([{ a: 1, b: 2 }]))
  await db.query('delete from users where id=$1', [user])
  assert.equal((await db.query('select id from fixer_requests where user_id=$1', [user])).rows.length, 0)
  assert.equal(await scalar('select fixer_request_id as value from estimate_line_proposals where id=$1', [proposal]), null, 'User removal preserves company proposal records without orphaning the request reference')
  await db.close()
  console.log('PASS: durable queue, user/estimate history, leases, staging, approval, recovery, RLS/grants and payload deduplication')
}

main().catch(error => { console.error(error); process.exitCode = 1 })
